import { Component, ViewChild } from '@angular/core';
import { PageHeaderComponent } from '../../../../../shared/components/page header/page-header-component/page-header-component';
import { MatDialog } from '@angular/material/dialog';
import { AddEmployeeComponent } from '../../components/add-employee/add-employee-component/add-employee-component';
import { MatTableDataSource, MatTableModule } from '@angular/material/table';
import {
  MatPaginator,
  MatPaginatorIntl,
  MatPaginatorModule,
  PageEvent,
} from '@angular/material/paginator';
import { Sort, MatSortModule, MatSort } from '@angular/material/sort';
import { IEmployeeRow } from '../../../../../core/models/requests';
@Component({
  selector: 'app-mange-employee-page',
  imports: [
    PageHeaderComponent,
    MatTableModule,
    MatPaginatorModule,
    MatSortModule,
  ],
  providers: [
    { provide: MatPaginatorIntl, useValue: getArabicPaginatorIntl() },
  ],
  templateUrl: './mange-employee-page.html',
  styleUrl: './mange-employee-page.css',
})
export class MangeEmployeePage {
  filter($event: any) {
    this.employees.filter = $event.target.value;
  }
  sortedData: IEmployeeRow[] = [];
  currentPage: number = 0;
  element: IEmployeeRow[] = [
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: '1',
      name: 'عبدالعزيز حسن',
      role: 'مدير عام',
      natId: '2234048409',
      countryCode: 'نيجيريا',
      email: 'bdalzyzalbrnawy47@gmail.com',
    },
    {
      id: 'e101',
      name: 'سارة الزهراني',
      role: 'محامية',
      natId: '1029384756',
      countryCode: 'السعودية',
      email: 'sarah.zahrani@lawfirm.sa',
    },
    {
      id: 'e102',
      name: 'خالد العتيبي',
      role: 'مساعد قانوني',
      natId: '2093847561',
      countryCode: 'الكويت',
      email: 'khaled.otaibi@lawfirm.sa',
    },
    {
      id: 'e103',
      name: 'ليلى الحربي',
      role: 'مديرة الموارد البشرية',
      natId: '3847561029',
      countryCode: 'الإمارات',
      email: 'layla.hr@lawfirm.sa',
    },
    {
      id: 'e104',
      name: 'عبدالله القرني',
      role: 'محاسب',
      natId: '8475610293',
      countryCode: 'السعودية',
      email: 'abdullah.finance@lawfirm.sa',
    },
    {
      id: 'e105',
      name: 'نورة الشمري',
      role: 'مديرة مكتب',
      natId: '5610293847',
      countryCode: 'قطر',
      email: 'noura.office@lawfirm.sa',
    },
    {
      id: 'e106',
      name: 'فهد الدوسري',
      role: 'مستشار قانوني',
      natId: '9384756102',
      countryCode: 'البحرين',
      email: 'fahad.consult@lawfirm.sa',
    },
  ];

  employees = new MatTableDataSource<IEmployeeRow>(this.element);

  @ViewChild(MatPaginator) paginator: MatPaginator = {} as MatPaginator;
  @ViewChild(MatSort) sort: MatSort = {} as MatSort;

  ngAfterViewInit() {
    this.employees.paginator = this.paginator;
    this.employees.sort = this.sort;
  }
  displayedColumns: string[] = [
    'positon',
    'name',
    'natId',
    'email',
    'role',
    'countryCode',
    'actions',
  ];
  constructor(private dialogof: MatDialog) {}

  addEmployee() {
    this.dialogof.open(AddEmployeeComponent, {
      height: '550px',
      minWidth: '400px',
    });
  }

  handelPage($event: PageEvent) {
    console.log($event);
  }
}

export function getArabicPaginatorIntl(): MatPaginatorIntl {
  const paginatorIntl = new MatPaginatorIntl();
  paginatorIntl.itemsPerPageLabel = 'عدد العناصر في الصفحة';
  paginatorIntl.nextPageLabel = 'الصفحة التالية';
  paginatorIntl.previousPageLabel = 'الصفحة السابقة';
  paginatorIntl.firstPageLabel = 'الصفحة الأولى';
  paginatorIntl.lastPageLabel = 'الصفحة الأخيرة';
  paginatorIntl.getRangeLabel = (page, pageSize, length) => {
    if (length === 0 || pageSize === 0) return `0 من ${length}`;
    const start = page * pageSize;
    const end = Math.min(start + pageSize, length);
    return `${start + 1} - ${end} من ${length}`;
  };
  return paginatorIntl;
}
